# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:6.0.0-rc1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json


CMD ["-f", "/usr/share/logstash/pipeline/logstash.conf"]